#!/usr/bin/env bash
if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="bin,i3,netflix,nvim,personal,tmux,uwuntu,xkb,zsh"
end

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/.dotfiles
end

set STOW_FOLDERS $STOW_FOLDERS
set DOTFILES $DOTFILES

$DOTFILES/install


